exports.PERIODS = {
  ACTIVATION: 0,
  DRAW: 1,
  VOTE: 2,
  APPEAL: 3,
  EXECUTE: 4
}
exports.DISPUTE_STATES = {
  OPEN: 0,
  RESOLVING: 1,
  EXECUTABLE: 2,
  EXECUTED: 3
}
exports.GAS_LIMIT = 150000
exports.NULL_ADDRESS = '0x'
